### ISSUE TITLE
mysides assertion failed

### ISSUE THREAD

**Issue by morgrowe** [mosen/mysides#3]
I've been using mysides to automatically place the user's network home directory in the sidebar during login via LoginHook. This worked perfectly in 10.10, but doesn't seem to work in 10.11.

The machine hangs during login and if I look in the log, I see these error messages appearing countless times:

> 3/4/16 11:47:41.199 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97
> 3/4/16 11:47:43.678 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97
> 3/4/16 11:47:47.174 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97
> 3/4/16 11:47:51.627 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97
> 3/4/16 11:47:57.109 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97
> 3/4/16 11:48:03.550 AM	mysides[310]	assertion failed: 15D21: libxpc.dylib + 24227 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x97

The command I'm using, that used to work on 10.10, but no longer works on 10.11 is: 

`sudo -u <USERNAME_HERE> /path/to/mysides add <USERNAME_HERE> file:///path/to/network/home/on/disk`

Is this something you've come across or understand the error? My original thought before posting this was that there was an issue with using sudo -u, but there are many other commands in the LoginHook that use sudo -u that work perfectly.

Thanks for all of your hard work on mysides!
Morgan

**Comment by morgrowe** [comment]
I thought I'd try 'converting' the script so that it runs via launchd (LaunchAgent), but a different error occurs this time, maybe this one is more helpful?

> loanmac-01 com.apple.xpc.launchd[1] (org.name.configure-sidebar[879]): Service could not initialize: 15D21: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd

Cheers!

**Comment by jimhuls** [comment]
morgrowe - I'm just now wrapping up a project that included me creating a user launchagent that mounts the user's network drive. The script that does the mounting and uses mysides to create a shortcut in the finder was converted into an application with Platypus. This allows a user to launch the mounting process  easily if needed. Early on I know I ran into some problems like you describe. 

I ended up creating a user based launchagent as a solution so that it was running in the user's space at login and not root. This presented some challenges but I think I finally got it. For 10.10 and 10.11 I had to use launchctl to do this while for 10.9 I used sudo. sudo might have worked for 10.10 but since launchctl worked, I left it. There could be a better way to do it but I was learning as I went and the scope of things was a bit more than what I've mentioned. At any rate I don't know if that helps but it might give you some ideas. Good luck!

**Comment by mosen** [comment]
If i had to guess there's some kind of XPC service that the LSSharedFileList API needs in order to work, that isn't launched yet when you are running the program. LaunchAgents would be one way to get around that. I believe the LoginHook via loginwindow.plist is deprecated?

**Comment by morgrowe** [comment]
@jimhuls Thanks for sharing. I too, in the end, went with a LaunchAgent that calls a script that runs in user space.

@mosen Ok, that makes sense. Using a LaunchAgent did resolve the issue for me.

Yes, LoginHooks have been deprecated for awhile now. It's a shame they're so good at preparing the user's experience before the user is able to interact with the machine. There's nothing worse, in my opinion, than having a LaunchAgent have to kill the Dock or the Finder to apply some configuration. However, in the case of mysides, you don't need to restart the Finder in order to use it, which is excellent.
